"""
@author: Alexis Oblet
"""


from PyQt4 import QtCore, QtGui
from src.ui.languageTreeMVC import LanguageTreeMVC
import os.path as op


class LanguageToolKit(QtGui.QWidget):
    """
    Util widget for Extinction developers.
    It makes the UI words insertion easier into the game.
    This is the bridge between developer and word insertion into Json file.
    Creates backups into LanguageTreeMVC.DIRNAME_BACKUP
    """

    KEY_PREFS_JSON_PATH = "jsonPath"

    def __init__(self):
        QtGui.QWidget.__init__(self)
        # self.showMaximized()
        self.setWindowIcon(QtGui.QIcon("img/app-icon.ico"))
        self.setWindowTitle("ELTK - Extinction Language Tool Kit")
        self.treeComponent = LanguageTreeMVC(self)

        # UI
        self.jsonChooser = QtGui.QPushButton("...")
        self.jsonPath = QtGui.QLineEdit()
        self.keyInput = QtGui.QLineEdit()
        self.valueInput = QtGui.QLineEdit()
        self.updateJson = QtGui.QPushButton("Update")
        self.removeJson = QtGui.QPushButton("Remove")
        self.saveButton = QtGui.QPushButton("Save to JSON")
        self.clearBackup = QtGui.QPushButton("Clear backup")
        self.autoGeneratedMessage = QtGui.QLineEdit(self)
        self.jsonComments = QtGui.QLineEdit(self)

        self.jsonCacheFolder = ''

        # Preferences
        self.prefs = QtCore.QSettings("ExtinctionTeam", "LanguageToolKit")

        self.setupUI()
        self.setupConnections()
        self.loadFromCache()

    def loadComments(self):
        if LanguageTreeMVC.KEY_AUTOGENERATED_MESSAGE in self.treeComponent.jsModel:
            self.autoGeneratedMessage.setText(self.treeComponent.jsModel[LanguageTreeMVC.KEY_AUTOGENERATED_MESSAGE])

        if LanguageTreeMVC.KEY_COMMENTS in self.treeComponent.jsModel:
            self.jsonComments.setText(self.treeComponent.jsModel[LanguageTreeMVC.KEY_COMMENTS])

    def onClickedJSON(self):
        jsonFile = QtGui.QFileDialog.getOpenFileName(self, "Select Json file", self.jsonCacheFolder, "*.json")
        if not jsonFile:
            return

        self.jsonCacheFolder = op.dirname(str(jsonFile))
        self.prefs.setValue(LanguageToolKit.KEY_PREFS_JSON_PATH, jsonFile)
        self.jsonPath.setText(jsonFile)
        self.treeComponent.load(jsonFile)

        self.loadComments()

    def onItemClicked(self, item):
        # on item clicked: fill input fields
        self.keyInput.setText(item.key)
        self.valueInput.setText(item.value)

    def setupConnections(self):
        self.jsonChooser.clicked.connect(self.onClickedJSON)
        self.treeComponent.itemClicked.connect(self.onItemClicked)

        self.updateJson.clicked.connect(self.onUpdateJsonTriggered)
        self.keyInput.returnPressed.connect(self.onUpdateJsonTriggered)
        self.valueInput.returnPressed.connect(self.onUpdateJsonTriggered)

        self.saveButton.clicked.connect(self.onSaveJSON)
        self.removeJson.clicked.connect(lambda: self.treeComponent.removeFromModel(self.keyInput.text()))
        self.keyInput.textChanged.connect(self.treeComponent.loadTree)

    def onUpdateJsonTriggered(self):
        self.treeComponent.addToModel(self.keyInput.text(), self.valueInput.text())

    def onSaveJSON(self):
        self.treeComponent.saveJson(self.jsonPath.text())
        self.loadComments()

    def loadFromCache(self):
        # Cache json path
        cacheJsonPath = self.prefs.value(LanguageToolKit.KEY_PREFS_JSON_PATH)
        cacheJsonPath = cacheJsonPath.toString() if cacheJsonPath else None

        if not cacheJsonPath or not op.exists(cacheJsonPath):
            return

        self.jsonCacheFolder = op.dirname(str(cacheJsonPath))
        self.jsonPath.setText(cacheJsonPath)
        self.treeComponent.load(cacheJsonPath)
        self.loadComments()

    def setupUI(self):
        self.setMinimumWidth(650)

        self.jsonChooser.setToolTip("Select Json File")
        self.updateJson.setToolTip("Update to Model")
        self.removeJson.setToolTip("Remove from Model")

        self.autoGeneratedMessage.setReadOnly(True)
        self.jsonComments.setReadOnly(True)
        self.jsonPath.setReadOnly(True)

        buttonsStyle = "QPushButton:checked{ border:none }"
        self.updateJson.setStyleSheet(buttonsStyle)
        self.removeJson.setStyleSheet(buttonsStyle)
        self.saveButton.setStyleSheet(buttonsStyle)

        layoutJson = QtGui.QHBoxLayout()
        layoutJson.addWidget(self.jsonPath)
        layoutJson.addWidget(self.jsonChooser)

        form = QtGui.QFormLayout()
        form.addRow("JSON Path ", layoutJson)
        form.addRow("JSON Comments ", self.jsonComments)
        form.addRow("ELTK Comments ", self.autoGeneratedMessage)
        form.addRow("Key UI ", self.keyInput)
        form.addRow("Value UI ", self.valueInput)

        paddingButton = "padding : 10px;"

        self.updateJson.setStyleSheet(paddingButton)
        self.removeJson.setStyleSheet(paddingButton)
        self.saveButton.setStyleSheet(paddingButton)

        layoutJsonButtons = QtGui.QHBoxLayout()
        layoutJsonButtons.addWidget(self.updateJson)
        layoutJsonButtons.addWidget(self.removeJson)
        # layoutJsonButtons.setAlignment(QtCore.Qt.AlignCenter)

        mainLayout = QtGui.QVBoxLayout()
        mainLayout.addLayout(form)
        mainLayout.addLayout(layoutJsonButtons)
        mainLayout.addWidget(self.saveButton)
        mainLayout.addSpacing(20)
        mainLayout.addWidget(self.treeComponent)
        mainLayout.setMargin(20)
        self.setLayout(mainLayout)

